PREFIX ds: <http://dados.gov.br/dataset/odm5_mortalidade_materna#> 
PREFIX RDF: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX ibge: <https://metadados.ibge.gov.br/#> 
PREFIX gn: <http://www.geonames.org/ontology#> 
PREFIX j.0: <http://w3c/future-csv-vocab/> 
PREFIX j.1: <file:///Users/amonrhaniery/eclipse-workspace/hierarquiaurbana/input/odm5_mortalidade_maternanone.csv#>
PREFIX sdmx-dimension: <http://purl.org/linked-data/sdmx/2009/dimension#>
PREFIX sdmx-measure: <http://purl.org/linked-data/sdmx/2009/measure#>
PREFIX sdmx-concept: <http://purl.org/linked-data/sdmx/2009/concept#>
PREFIX qb: <http://purl.org/linked-data/cube#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX dcat: <http://www.w3.org/ns/dcat#>

CONSTRUCT {

    ?refCidade a qb:DimensionProperty;
        rdfs:subPropertyOf sdmx-dimension:refArea;
        qb:concept sdmx-concept:refArea;
        rdfs:range gn:P.

    ?dsObito a qb:MeasureProperty;
        rdfs:subPropertyOf sdmx-measure:obsValue;
        rdfs:label "Percentual de óbitos de mulheres em idade fértil investigados"@pt;
        rdfs:label "Percentage of deaths of women of childbearing age investigated"@en;
        qb:concept 	<http://vocabularies.unesco.org/thesaurus/concept5070> ;
        rdfs:range xsd:decimal.

    ?componente qb:measure ?dsObito ; 
        qb:dimension sdmx-dimension:refPeriod ; 
        qb:dimension ?refCidade .

    ?dsd a qb:DataStructureDefinition;
        qb:component ?componente.

    ?csv a dcat:Distribution;
        dcat:downloadURL ?downuri;
        dcat:mediaType "text/csv" .

    ?odm5_mortalidade_materna a qb:DataSet;
        rdfs:label "Percentual de óbitos de mulheres em idade fértil investigados"@pt;
        rdfs:label "Pecentage of deaths of women of childbearing age investigated"@en;
        rdfs:comment "Número de óbitos de mulheres em idade fértil (10a 49 anos) notificados ao SIM, com ficha síntese digitada no módulo de investigaçãodo SIM.Periodicidade de Atualização: Anual Método de Cálculo: Cobertura = Valor absoluto" ;
        a dcat:Dataset;
        dcat:landingPage ?uri;
        dcat:distribution ?csv;
        qb:structure ?dsd.

    ?row a qb:Observation ;
        ds:obitos ?indicx;
        qb:dataSet ?odm5_mortalidade_materna;
        sdmx-dimension:refPeriod "2018"^^xsd:integer;
        ds:refCidade ?city.
        
        ?city a ibge:Cidade;
            gn:name ?nome.
        
} WHERE {
?row j.1:no_cidade ?nome;
    j.1:indicx ?indicx .
    BIND(ENCODE_FOR_URI( STR( ?nome ) ) AS ?nome2)
    BIND(URI(CONCAT("https://cidades.ibge.gov.br/#", STR( ?nome2 )))  AS ?city)
    BIND(URI("http://dados.gov.br/dataset/odm5_mortalidade_materna")AS ?uri)
    BIND(URI("http://i3geo.saude.gov.br/i3geo/ogc.php?service=WFS&version=1.0.0&request=GetFeature&typeName=odm5_mortalidade_materna&outputFormat=CSV")AS ?downuri)
    BIND(URI("http://dados.gov.br/dataset/odm5_mortalidade_materna")AS ?odm5_mortalidade_materna)
    BIND(URI("http://dados.gov.br/dataset/odm5_mortalidade_materna#dsd")AS ?dsd)
    BIND(URI("http://dados.gov.br/dataset/odm5_mortalidade_materna#componente")AS ?componente)
    BIND(URI("http://dados.gov.br/dataset/odm5_mortalidade_materna#csv")AS ?csv)
    BIND(URI(CONCAT("http://dados.gov.br/dataset/odm5_mortalidade_materna#", "obitos"))  AS ?dsObito)
    BIND(URI(CONCAT("http://dados.gov.br/dataset/odm5_mortalidade_materna#", "refCidade"))  AS ?refCidade)
}